### ISSUE TITLE
requirement、artifact、interface解析现在做了吗

### ISSUE THREAD

**Issue by ns7381** [pqnet/tosca-yaml-parser#2]

**Comment by pqnet** [comment]
The project has been abandoned for lack of funding.  Feel free to take it over if you find anything interesting.

**Comment by ns7381** [comment]
So do you have any other project that can substitute this project and is more perfect.?And can you give me to learn?Thank you for answer.

**Comment by pqnet** [comment]
no i'm not working on service computing anymore
